;; * Emacs Init Code
;; Maintained by jgd
;; NOT byte-compiled
;; Anything complicated should be migrated to a byte-compiled file
;; under NGender if it's fairly generic
;; under JGD otherwise

;; Attempted workaround for font prem in 24.3.1
 ;; (setq initial-frame-alist '(
 ;; 	 (font . "Monospace-10")
 ;; 	 (vertical-scroll-bars . right)
 ;; ))
 ;; (setq default-frame-alist '(
 ;;   (font . "Monospace-10")
 ;; 	 (vertical-scroll-bars . right)
 ;; ))

;; ** Packages

(require 'package)
(defvar my-archives
	'( ("gnu" . "http://elpa.gnu.org/packages/")
		 ("marmalade" . "http://marmalade-repo.org/packages/")
		 ("melpa-stable" . "http://melpa-stable.milkbox.net/packages/")
		 ("org" . "https://orgmode.org/elpa/") ) )
(dolist (a my-archives)	(add-to-list 'package-archives a t))
(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents) )

;; Is this redundant given list-packages??
(defvar my-packages '(
	auto-complete
	cider
	company
	git-commit
	helm
	ido-ubiquitous
	magit
	magithub
	markdown-mode
	multi-term
	mysql-to-org
	org
	org-autolist
	org-bullets
	org-page
	org-projectile
	org-tree-slide
	ox-gfm
	paredit-everywhere
	persp-mode
	php-mode
	project-mode
	rainbow-delimiters
	racer
	rust-mode
	sql
	sql-indent
	sqlup-mode
	smex
	toc-org
	typed-clojure-mode
	use-package
)
  "A list of packages to ensure are installed at launch.")

; This is not working on ngender.org, Friday 21 April 2017, !!!
(dolist (p my-packages)
  (unless (package-installed-p p)
    (package-install p) ) )

(require 'multi-term)

;; ** Font and Pitch Preferences

(defvar *ngender-pitch-mode* :variable)
(defvar *ngender-fixed-font* "Dejavu Sans Mono")
(defvar *ngender-variable-font* "Dejavu Sans Condensed")
(defvar *ngender-font* *ngender-variable-font*)
(defvar *ngender-frame-font* *ngender-font*)
;		 "-adobe-courier-medium-r-normal--%d-*-*-*-m-*-iso8859-1"

;; ** Load-Paths

(dolist (p '( "~/Lib/Emacs" "~/.emacs.d/vendor"
	      "~/.emacs.d/JGD" "~/.emacs.d/NGender"
	      "~/.emacs.d/vendor/ensime/elisp/"
	      "~/.emacs.d/vendor/html5-el/" ) )
  (add-to-list 'load-path p) )

;; ** Load Packages

;; *** Load NGender Packages
;; Should instead arrange for most of them to autoload!!

;; Report an error if not found, say nothing if all goes well
;; (load "ngender" nil t)
;; (load "ngender-rx" nil t)
;; (load "ngender-org" nil t)
;; (load "ngender-shell" nil t)
;; (load "ngender-elisp" nil t)
;; (load "ngender-sql" nil t)
;; (load "my-sql-pw" nil t)
;; (load "ngender-sql-connect" nil t)

;; *** Load JGD Packages

;; Report an error if not found, say nothing if all goes well
;; (load "jgd" nil t)	; my fancy code in ~/.emacs.d/jgd

;; *** Key Bindings - (Re)Define some keyboard shortcuts

(global-set-key "\C-x\C-b" 'bs-show)
(global-set-key "\C-cv" 'buffer-face-mode)
(global-set-key (kbd "C-x g") 'magit-status)

;; *** WindMove

(windmove-default-keybindings 'meta)

;; *** Uniquify
;; (require 'uniquify)

;; Workaround to hopefully get rid of annoying:
;; Save Error: "Unbalanced parentheses": /home/greg/.emacs.d/semanticdb/!home!greg!Play!Lang!Lisps!ClojureScript!modern-cljs!resources!public!semantic.cache
; This was working, but now:
; Symbol's function definition is void: global-semantic-show-unmatched-syntax-mode
; (global-semantic-show-unmatched-syntax-mode -1)

;; *** html5 editing

;; (eval-after-load "rng-loc"
;;   '(add-to-list 'rng-schema-locating-files "~/code/html5-el/schemas.xml"))

; This is not working on ngender.org, Friday 21 April 2017, !!!
; (require 'whattf-dt)

;; this font works via set-frame-font so let's write a function
;; using format to put in the desired size!
;; -unknown-DejaVu Sans-normal-normal-semicondensed-*-*-*-*-*-*-0-iso10646-1


;; *** j-lang Support
;; https://github.com/zellio/j-mode

;; (add-to-list 'load-path "~/.emacs.d/j-mode/")
;; (autoload 'j-mode "j-mode.el" "Major mode for editing J files" t)
;; (add-to-list 'auto-mode-alist '("\\.ij[rstp]$" . j-mode))

;; *** Company

;; Enable company globally for all mode
; (global-company-mode)

;; Reduce the time after which the company auto completion popup opens
; (setq company-idle-delay 0.2)

;; Reduce the number of characters before company kicks in
; (setq company-minimum-prefix-length 1)

;; *** Tramp

(setq tramp-default-method "ssh")

;; ** Miscellaneous

; Somehow M-; got rebound to something weird so reset it
(global-set-key (kbd "M-,") 'tags-loop-continue)

; (workgroups-mode 1)

;; ** Key Settings

;; *** ignore keysyms generated by my flakey Dell Studio
(global-set-key [XF86AudioMedia] 'ignore)
(global-set-key [C-XF86AudioMedia] 'ignore)
(global-set-key [M-XF86AudioMedia] 'ignore)
(global-set-key [XF86AudioPrev] 'ignore)
(global-set-key [C-XF86AudioPrev] 'ignore)

;; *** Handy Meta-Arrow bindings
(global-set-key [M-left]  'beginning-of-line)
(global-set-key [M-right] 'end-of-line)
(global-set-key [M-up]    'move-to-top-of-window)
(global-set-key [M-down]  'move-to-bottom-of-window)

;; Make Control-W kill the word to the left of the cursor
;; just like it works within a shell command line.
(global-set-key [?\C-w] 'backward-kill-word)
(global-set-key [C-backspace] 'kill-region) ; was C-W

;; the "*-region-or-word" functions don't seem to exist in gnu emacs
;; (global-set-key [?\M-c] 'capitalize-region-or-word)
;; (global-set-key [?\M-C] 'upcase-region-or-word)

;; *** Super bindings
(global-set-key [?\s-c] 'upcase-word)
(global-set-key [s-prior] 'ngender-previous-window)
(global-set-key [s-next] 'ngender-next-window)
(global-set-key [?\s-\;] 'comment-region)
(global-set-key [?\s-\:] 'uncomment-region)

;; *** Bindings for Control plus a function key:

(global-set-key [C-f1] 'help-command)	; press f1 for help
(global-set-key [C-f2] 'shell)	; get a Unix shell in a window
(global-set-key [C-f3] 'compile)	; compile (make) something
(global-set-key [C-f4] 'next-error)	; visit the next compilation error
(global-set-key [C-f5] 'undo)		; Keep pressing it to undo more
(global-set-key [C-f7] 'blink-matching-open)	;  matching parens
(global-set-key [C-f8] 'start-kbd-macro)	; start recording commands
(global-set-key [C-f9] 'end-kbd-macro)	; finish and call it a macro
(global-set-key [C-f10] 'call-last-kbd-macro)	; re-execute the macro
;; (global-set-key [M-f11] 'upcase-word)
(global-set-key [C-f12] 'repeat-complex-command)

;; *** Set some miscellaneous variables
(setq visible-bell t)
(setq tab-stop-list nil)
(setq inhibit-startup-screen t)

;; ** Loading desired NGender and JGD Modules

;; (require 'jgd)
;; (require 'ngender)
;; (require 'ngender-org)
;; (add-to-list 'auto-mode-alist '("\\.org\\'" . ngender-org-mode)
;; (require 'ngender-sql)
;; (add-to-list 'auto-mode-alist '("\\.sql\\'" . ngender-sql-mode)
;; (require 'ngender-sql-connect)
;; (require 'my-sql-pw)

;; ** Not Yet Loading NGender and JGD Modules
;; *** ngender-cedet
;; (require 'ngender-cedet)
;; *** ngender-clisp
;; (require 'ngender-clisp)
;; *** ngender-sql-test
;; (require 'ngender-sql-test)
;; *** ox-tiki
;; (require 'ox-tiki)

;; ** AutoLoading NGender Modules

;; *** ngender-c
;; (autoload 'ngender-c-mode "ngender-c")
;; (add-to-list 'auto-mode-alist '("\\.[cChH]\\(pp\\|PP\\|xx\\|XX\\|++\\|\\)\\'" . ngender-c-mode)

;; *** ngender-clojure
;; (autoload 'ngender-clojure-mode "ngender-clojure")
;; (add-to-list 'auto-mode-alist '("\\.\\(clj[cxs]\\?\\|dtm\\|edn\\)\\'" . ngender-clojure-mode))

;; *** ngender-haskell
;; (autoload 'ngender-haskell-mode "ngender-haskell")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-haskell-mode))

;; **** ngender-mozart
;; (require "ngender-mozart")
;; (autoload 'ngender-mozart-mode "ngender-mozart")
;; (add-to-list 'auto-mode-alist '("\\.oz\\'" . ngender-mozart-mode)

;; **** ngender-php
;; (autoload 'ngender-php-mode "ngender-php")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-php-mode)
;; **** ngender-prolog
;; (autoload 'ngender-prolog-mode "ngender-prolog")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-prolog-mode)
;; **** ngender-rust
;; (autoload 'ngender-rust-mode "ngender-rust")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-rust-mode)
;; **** ngender-rx
;; (autoload 'ngender-rx-mode "ngender-rx")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-rx-mode)
;; **** ngender-shell
;; (autoload 'ngender-shell-mode "ngender-shell")
;; (add-to-list 'auto-mode-alist '("\\.foo\\'" . ngender-shell-mode)

;; Load rust-mode when you open `.rs` files
(add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-mode))

;; ** Ensuring utility buffers exist

; Let's make sure that these handy buffers exist
(dolist (buffer '("*SQL*" "*compilation*" "*shell*"))
	(get-buffer-create buffer) )

;; ** Activate simple Global Modes

(winner-mode 1)
(menu-bar-mode 1)              ;  it got disabled somewhere!

;; ** Start the Emacs-Server

(server-start)
