#!/bin/bash
: << 'EOF'
;; * Generate Org-Mode list of ngender-*.el files in this directory -*- -*-
EOF
for f in ${0##*/} ngender-*.el; do
printf -- '- [[%s]] :: %s\n' "$f" \
	"$(head "$f" | sed -n 's/^;; \* \(.*[^[:space:]]\)[[:space:]]*-\*-.*-\*-.*/\1/p')"
done
