* Status of NGender Emacs Prelude Project

** Overall Status: Rough

- Some modules are good enough for now.
- Many modules are unreliable
- ngender-example needs to show the way

** Roadmap

As ngender-example gets close to completion, examine what we
can add to ngender.el to make it simpler.  All of the
management of packages and features should be made much
simpler.  To make list filtering easier it will be useful to
define a flatten function to run after any filtering which
is producing an output list not in a 1-to-1 correspondence
with the input list.
	 
Let's dump cl-lib in favor of seq.  Let's not pull in
dash, despite its beauty.

What other now built-in packages would be helpful?

We should be using Xref instead of directly using tag commands!

Which project-management package(s) should we provide?
There's a new built-in package "project".
	
** Missing Package problems

The absence of these were causing problems:
- auto-complete
- evil-leader

** Warnings

Warning (type): Expected directory, got /usr/share/texmf/doc/info/
Warning (type): Expected directory, got /home/greg/.emacs.d/themes [2 times]
