#+TITLE: NGender layer

* Emacs Profile Ideas

** NOTICE OF GitHub FAILURE
  - As of 2026-10-01 GitHub is failing to correctly display this document!
  - See the section below titled: ** Availability Of This Document


This is an old mess from before I moved to Spacemacs, /except for/

- [[file:org-capture.el][org-capture.el]] :: my org-capture set up

Note that the files under ~/Notes/GTD folder (or wherever you put them) have to
already exist and have the assumed OrgMode structure for org-capture to work.

- [[file:.spacemacs][.spacemacs]] :: my spacemacs settings

May contain useful clues on how to set up Org-Babel for various programs.
** Availability Of This Document

This document is normally available at all the following urls:
- Codeberg :: 
- GitLab :: 
- GitHub ::
  - GitHub is currently failing to correctly process OrgMode documents.
  - as of 2026-10-01

Please consult the LICENCE or LICENSE.org or LICENSE.md file at the
top of this repository for freedoms and restrictions in your use of
the contents of this repository, including this document.

Even when not required, we would appreciate
- attribution with a reference to our respository,
- your sending us any improvements you make to these materials,
- information about any significant usage of these materials in your projects,
- and thank you!
